# Generated by Django 5.2.4 on 2025-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=200, verbose_name='Marca')),
                ('factory_year', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('model_year', models.DateField(blank=True, null=True, verbose_name='Ano do Modelo')),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Clientes',
                'ordering': ['model'],
            },
        ),
    ]
