# Generated by Django 5.2.4 on 2025-07-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterField(
            model_name='car',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço'),
        ),
    ]
