# Generated by Django 5.2.4 on 2025-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField(verbose_name='Quantidade')),
                ('cars_value', models.FloatField(verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Inventário',
                'ordering': ['-created_at'],
            },
        ),
    ]
